#!/usr/bin/env bash

set -o errexit
set -o pipefail

DC="${DC:-exec}"

# If we're running in CI we need to disable TTY allocation for docker compose
# commands that enable it by default, such as exec and run.
TTY=""
if [[ ! -t 1 ]]; then
  TTY="-T"
fi

# -----------------------------------------------------------------------------
# Helper functions start with _ and aren't listed in this script's help menu.
# -----------------------------------------------------------------------------

function _dc {
  docker compose "${DC}" ${TTY} "${@}"
}

function _build_run_down {
  docker compose build
  docker compose run ${TTY} "${@}"
  docker compose down
}

# -----------------------------------------------------------------------------

function cmd {
  # Run any command you want in the api container
  _dc api "${@}"
}

function rails {
  # Run any Rails commands
  cmd rails "${@}"
}

function test {
  # Run your Rails tests, use `test -b` to first rebuild your JS and CSS
  local run_build="${1:-}"
  local test_command="rails test"

  if [ "${run_build}" = "-b" ]; then
    test_command="yarn build && yarn build:css && ${test_command}"
  fi

  _dc -e "RAILS_ENV=test" js bash -c "${test_command}"
}

function shell {
  # Start a shell session in the web container
  cmd bash "${@}"
}

function mysql {
  # Connect to PostgreSQL with psql
  # shellcheck disable=SC1091
  . .env
  _dc db mysql -u root -pzelucash
}

function redis-cli {
  # Connect to Redis with redis-cli
  _dc redis redis-cli "${@}"
}

function bundle:install {
  # Install Ruby dependencies and write out a lock file
  _build_run_down web bundle install
}

function bundle:outdated {
  # List any installed gems that are outdated
  cmd bundle outdated
}

function bundle:update {
  # Update any installed gems that are outdated
  cmd bundle update
  bundle:install
}

function clean {
  # Remove cache and other machine generates files
  rm -rf node_modules/ app/assets/builds/* public/assets tmp/* .byebug_history
}

function help {
  printf "%s <task> [args]\n\nTasks:\n" "${0}"

  compgen -A function | grep -v "^_" | cat -n

  printf "\nExtended help:\n  Each task has comments for general usage\n"
}

# This idea is heavily inspired by: https://github.com/adriancooney/Taskfile
TIMEFORMAT=$'\nTask completed in %3lR'
time "${@:-help}"